"""core domain: users, groups, applications, audit chain

Revision ID: 6ae303c8b4a1
Revises:
Create Date: 2026-08-13 19:50:13.464178+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6ae303c8b4a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "slug",
            sa.String(length=64),
            nullable=False,
            comment="URL-safe identifier used in console routes.",
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "protocol",
            sa.Enum(
                "saml2", "oidc", "scim2", "none", name="appprotocol", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="appstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "entity_id",
            sa.String(length=500),
            nullable=True,
            comment="SAML EntityID of the service provider. Globally unique by spec, so the constraint is the spec's, not ours.",
        ),
        sa.Column(
            "acs_url",
            sa.String(length=500),
            nullable=True,
            comment="Assertion Consumer Service — where we POST the assertion.",
        ),
        sa.Column("slo_url", sa.String(length=500), nullable=True),
        sa.Column("nameid_format", sa.String(length=200), nullable=True),
        sa.Column(
            "signing_cert",
            sa.Text(),
            nullable=True,
            comment="The SP's X.509 certificate, PEM. Used to verify AuthnRequests.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("entity_id", name=op.f("uq_applications_entity_id")),
        sa.UniqueConstraint("name", name=op.f("uq_applications_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_applications_slug")),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum("user", "system", "idp", name="actortype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_label",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable actor, denormalised at write time so the entry still reads correctly after the actor is gone.",
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="Dotted verb, e.g. 'user.created', 'group.member_added', 'saml.login'. Stable strings — dashboards group on them.",
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "success", "failure", "denied", name="auditoutcome", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("target_label", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "correlation_id",
            sa.Uuid(),
            nullable=True,
            comment="Ties every event produced by one request or one sync run together. P6 relies on this to show a whole provisioning cascade.",
        ),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Event-specific payload. In P2 this holds the decoded SAML assertion and its per-check validation results.",
        ),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 over this event's canonical form plus prev_hash.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_events_hash")),
    )
    op.create_index("ix_audit_events_action", "audit_events", ["action"], unique=False)
    op.create_index("ix_audit_events_actor_id", "audit_events", ["actor_id"], unique=False)
    op.create_index(
        "ix_audit_events_correlation_id", "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_occurred_at", "audit_events", [sa.text("occurred_at DESC")], unique=False
    )
    op.create_index("ix_audit_events_outcome", "audit_events", ["outcome"], unique=False)
    op.create_index(
        "ix_audit_events_target", "audit_events", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "external_id",
            sa.String(length=255),
            nullable=True,
            comment="SCIM externalId for the group in the upstream IdP.",
        ),
        sa.Column(
            "source",
            sa.Enum(
                "scim", "jit", "manual", "seed", name="identitysource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "hrms_role",
            sa.String(length=64),
            nullable=True,
            comment="Role granted in the downstream HRMS by virtue of this membership. Group-derived rather than per-user, which is the whole point of group-based access.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("external_id", name=op.f("uq_groups_external_id")),
        sa.UniqueConstraint("name", name=op.f("uq_groups_name")),
    )
    op.create_table(
        "users",
        sa.Column(
            "external_id",
            sa.String(length=255),
            nullable=True,
            comment="SCIM externalId — the IdP's own identifier for this person.",
        ),
        sa.Column(
            "user_name",
            sa.String(length=255),
            nullable=False,
            comment="SCIM userName. Usually the UPN or email. Stable login identifier.",
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("given_name", sa.String(length=128), nullable=True),
        sa.Column("family_name", sa.String(length=128), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="SCIM active. Deactivation is a soft delete — audit history and past access must remain inspectable after someone leaves.",
        ),
        sa.Column("employee_number", sa.String(length=64), nullable=True),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("job_title", sa.String(length=128), nullable=True),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column(
            "platform_role",
            sa.Enum(
                "admin",
                "helpdesk",
                "auditor",
                "employee",
                name="platformrole",
                native_enum=False,
                length=32,
            ),
            server_default="employee",
            nullable=False,
            comment="What this person can do in this console. P4 derives this from entitlement grants instead of storing it directly.",
        ),
        sa.Column(
            "source",
            sa.Enum(
                "scim", "jit", "manual", "seed", name="identitysource", native_enum=False, length=32
            ),
            nullable=False,
            comment="Provenance. A SCIM-sourced user edited by hand will be silently reverted by the next sync, so the UI blocks it.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
            name=op.f("fk_users_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_id", name=op.f("uq_users_external_id")),
        sa.UniqueConstraint("user_name", name=op.f("uq_users_user_name")),
    )
    op.create_index("ix_users_active", "users", ["active"], unique=False)
    op.create_index("ix_users_department", "users", ["department"], unique=False)
    op.create_index("ix_users_display_name", "users", ["display_name"], unique=False)
    op.create_index("ix_users_manager_id", "users", ["manager_id"], unique=False)
    op.create_table(
        "app_assignments",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role",
            sa.String(length=64),
            nullable=True,
            comment="Role granted inside the target application, e.g. 'Employee'.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(user_id IS NOT NULL) <> (group_id IS NOT NULL)",
            name=op.f("ck_app_assignments_exactly_one_principal"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_app_assignments_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_app_assignments_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_app_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_assignments")),
        sa.UniqueConstraint("application_id", "group_id", name="one_per_group"),
        sa.UniqueConstraint("application_id", "user_id", name="one_per_user"),
    )
    op.create_index(
        "ix_app_assignments_application_id", "app_assignments", ["application_id"], unique=False
    )
    op.create_index("ix_app_assignments_group_id", "app_assignments", ["group_id"], unique=False)
    op.create_index("ix_app_assignments_user_id", "app_assignments", ["user_id"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_members_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_group_members")),
    )
    op.create_index("ix_group_members_user_id", "group_members", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Make the audit log add-only, in the database itself.
    #
    # The fingerprints tell you if something was changed. These rules stop the
    # usual ways of changing it in the first place. Doing it in the database
    # rather than in our code means it also applies to psql, to a migration, to
    # a bug in our own code, and to anything else that gets a connection string.
    #
    # What it doesn't cover: whoever owns the table can turn these off again, so
    # this stops mistakes rather than a determined person with database access.
    # scripts/seed.py does exactly that to wipe a dev database.
    # -------------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_events_block_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only; % is blocked', TG_OP
                USING ERRCODE = 'restrict_violation',
                      HINT = 'Correct a mistaken entry by appending a compensating event.';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_no_update_or_delete
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_block_mutation();
        """
    )
    # TRUNCATE skips row-level triggers completely, so it needs its own. The
    # function only looks at which operation happened, never at row contents,
    # which is why the same one works for both.
    op.execute(
        """
        CREATE TRIGGER audit_events_no_truncate
        BEFORE TRUNCATE ON audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION audit_events_block_mutation();
        """
    )


def downgrade() -> None:
    # Drop the triggers first. Dropping the table would remove them anyway, but
    # spelling it out means this doesn't depend on the order below.
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events;")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_update_or_delete ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS audit_events_block_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_group_members_user_id", table_name="group_members")
    op.drop_table("group_members")
    op.drop_index("ix_app_assignments_user_id", table_name="app_assignments")
    op.drop_index("ix_app_assignments_group_id", table_name="app_assignments")
    op.drop_index("ix_app_assignments_application_id", table_name="app_assignments")
    op.drop_table("app_assignments")
    op.drop_index("ix_users_manager_id", table_name="users")
    op.drop_index("ix_users_display_name", table_name="users")
    op.drop_index("ix_users_department", table_name="users")
    op.drop_index("ix_users_active", table_name="users")
    op.drop_table("users")
    op.drop_table("groups")
    op.drop_index("ix_audit_events_target", table_name="audit_events")
    op.drop_index("ix_audit_events_outcome", table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_correlation_id", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_id", table_name="audit_events")
    op.drop_index("ix_audit_events_action", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("applications")
    # ### end Alembic commands ###
