"""access requests

Somebody asking to be put in a group, and somebody answering.

Two CHECK constraints carry the rules that make the approval step worth having,
and both are scoped to approved and denied rather than to every state. That
scoping is the point: a withdrawal is also somebody closing their own request, and
there the requester is the correct author. The rule is about who may *decide*, not
about who may write to the row — a constraint covering all states refuses every
withdrawal, which is how this was found.

Revision ID: 50c7528efa91
Revises: b4ad15a8cfa2
Create Date: 2026-08-17 18:36:38.175940+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "50c7528efa91"
down_revision: str | None = "b4ad15a8cfa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_requests",
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column(
            "requester_label",
            sa.String(length=255),
            nullable=False,
            comment="Copy of their name at the time, so the request still reads properly if their record changes or goes.",
        ),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("group_label", sa.String(length=255), nullable=False),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
            comment="Why they need it. Required, because an approver with no reason in front of them is rubber-stamping rather than deciding.",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "withdrawn",
                "cancelled",
                name="requeststate",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_by_id", sa.Uuid(), nullable=True),
        sa.Column("decided_by_label", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "decision_note",
            sa.Text(),
            nullable=True,
            comment="What the approver said. The most useful column here during a review, and the one most likely to be left empty.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="If approved, when the access should end. Carried onto the membership so temporary access is temporary.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state NOT IN ('approved', 'denied') OR (decided_by_label IS NOT NULL AND decided_at IS NOT NULL)",
            name=op.f("ck_access_requests_a_decision_has_an_author"),
        ),
        sa.CheckConstraint(
            "state NOT IN ('approved', 'denied') OR decided_by_id IS NULL OR decided_by_id <> requester_id",
            name=op.f("ck_access_requests_approver_is_not_the_requester"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_access_requests_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_access_requests_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_access_requests_requester_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_requests")),
    )
    op.create_index(
        "ix_access_requests_requester",
        "access_requests",
        ["requester_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_access_requests_state",
        "access_requests",
        ["state"],
        unique=False,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_index(
        "one_open_request_per_person_and_group",
        "access_requests",
        ["requester_id", "group_id"],
        unique=True,
        postgresql_where=sa.text("state = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "one_open_request_per_person_and_group",
        table_name="access_requests",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_index(
        "ix_access_requests_state",
        table_name="access_requests",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_index("ix_access_requests_requester", table_name="access_requests")
    op.drop_table("access_requests")
    # ### end Alembic commands ###
