"""record which applications we signed people into

The table single logout needs, and whose absence made it impossible.

Every assertion we issue carries a SessionIndex — our name for that login — and an
application quotes it back when asking us to sign somebody out. Nothing was storing
it, so there was no way to match a logout request to anything, and /idp/slo could
not have worked however it was written.

saml_session_id is ON DELETE SET NULL rather than CASCADE on purpose. The record of
having been signed in to an application should outlive the browser session that did
it: "they were in the finance system that afternoon" is asked after an incident, and
a cascade would have removed the answer.

Revision ID: cd874ea16c13
Revises: 14ef89863e9e
Create Date: 2026-08-19 06:29:44.279227+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cd874ea16c13"
down_revision: str | None = "14ef89863e9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idp_sessions",
        sa.Column(
            "saml_session_id",
            sa.Uuid(),
            nullable=True,
            comment="The browser session this login came from. Goes null rather than cascading, because the record of having signed in should outlive the session that did it.",
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "session_index",
            sa.String(length=128),
            nullable=False,
            comment="Our name for this login, as it appeared in the assertion. What an application quotes back when it asks us to sign the person out.",
        ),
        sa.Column(
            "name_id",
            sa.String(length=255),
            nullable=False,
            comment="The subject we told the application about. A logout request may name this instead of the session index, so both are searchable.",
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_reason", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_idp_sessions_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["saml_session_id"],
            ["saml_sessions.id"],
            name=op.f("fk_idp_sessions_saml_session_id_saml_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idp_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idp_sessions")),
        sa.UniqueConstraint("session_index", name="one_login_per_session_index"),
    )
    op.create_index(
        "ix_idp_sessions_application", "idp_sessions", ["application_id", "ended_at"], unique=False
    )
    op.create_index("ix_idp_sessions_name_id", "idp_sessions", ["name_id"], unique=False)
    op.create_index(
        "ix_idp_sessions_saml_session", "idp_sessions", ["saml_session_id"], unique=False
    )
    op.create_index(
        "ix_idp_sessions_session_index", "idp_sessions", ["session_index"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_idp_sessions_session_index", table_name="idp_sessions")
    op.drop_index("ix_idp_sessions_saml_session", table_name="idp_sessions")
    op.drop_index("ix_idp_sessions_name_id", table_name="idp_sessions")
    op.drop_index("ix_idp_sessions_application", table_name="idp_sessions")
    op.drop_table("idp_sessions")
    # ### end Alembic commands ###
