"""access rules and membership provenance

Adds the rules that grant group membership from somebody's attributes, and the
`source` column on group_members that makes them safe to run.

That column is the load-bearing part. Three things add memberships — the provider,
a person in the console, and now a rule — and the rule engine has to take back
only what it put there. Without provenance it would delete rows authentik
believes in, authentik would recreate them on the next sync, and the two would
loop forever.

The backfill at the end matters for the same reason. Every existing membership
would otherwise default to 'manual', which would claim a thousand rows authentik
created were typed in by hand. They are marked from the group they belong to: a
group the provider created has provider-created members.

Revision ID: b4ad15a8cfa2
Revises: 7ba689707a21
Create Date: 2026-08-17 18:04:52.598261+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b4ad15a8cfa2"
down_revision: str | None = "7ba689707a21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_rules",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="What this rule is for, in words. Shows up in the audit log.",
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Turning a rule off takes back what it granted, on the next run.",
        ),
        sa.Column(
            "attribute",
            sa.String(length=64),
            nullable=False,
            comment="Which user field to look at. Has to be one of rules.ATTRIBUTES.",
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "equals",
                "not_equals",
                "contains",
                "starts_with",
                "is_set",
                "is_not_set",
                name="ruleoperator",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=True,
            comment="What to compare against. Null for is_set and is_not_set.",
        ),
        sa.Column(
            "group_id",
            sa.Uuid(),
            nullable=False,
            comment="The group people matching this rule go into.",
        ),
        sa.Column(
            "created_by_label",
            sa.String(length=255),
            nullable=False,
            comment="Who wrote the rule. A copy of their name, so it survives their record being deleted.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_access_rules_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_rules")),
        sa.UniqueConstraint(
            "attribute", "operator", "value", "group_id", name="one_rule_per_condition_and_group"
        ),
        sa.UniqueConstraint("name", name=op.f("uq_access_rules_name")),
    )
    op.create_index(
        "ix_access_rules_enabled",
        "access_rules",
        ["enabled"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_index("ix_access_rules_group_id", "access_rules", ["group_id"], unique=False)
    op.add_column(
        "group_members",
        sa.Column(
            "source",
            sa.Enum(
                "scim",
                "manual",
                "rule",
                "seed",
                name="membershipsource",
                native_enum=False,
                length=32,
            ),
            server_default="manual",
            nullable=False,
            comment="Why they are in this group. Only 'rule' rows are ever removed by the rule engine.",
        ),
    )
    op.add_column(
        "group_members",
        sa.Column(
            "added_by_rule_id",
            sa.Uuid(),
            nullable=True,
            comment="Which rule put them here, when source is 'rule'. Goes null if the rule is deleted, which leaves the membership in place rather than quietly removing somebody's access as a side effect.",
        ),
    )
    op.create_index(
        "ix_group_members_user_source", "group_members", ["user_id", "source"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_group_members_added_by_rule_id_access_rules"),
        "group_members",
        "access_rules",
        ["added_by_rule_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Backfill the provenance rather than letting everything claim to be manual.
    #
    # Inferred from the group, which is the only evidence there is: nobody recorded
    # why these memberships existed, because until now there was nowhere to record
    # it. A group the provider created has provider-created members, and a seeded
    # group has seeded ones. Anything else stays 'manual', which for a group
    # somebody made by hand is also the truthful answer.
    op.execute(
        """
        UPDATE group_members AS gm
        SET source = CASE g.source
            WHEN 'scim' THEN 'scim'
            WHEN 'seed' THEN 'seed'
            ELSE 'manual'
        END
        FROM groups AS g
        WHERE g.id = gm.group_id
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_group_members_added_by_rule_id_access_rules"), "group_members", type_="foreignkey"
    )
    op.drop_index("ix_group_members_user_source", table_name="group_members")
    op.drop_column("group_members", "added_by_rule_id")
    op.drop_column("group_members", "source")
    op.drop_index("ix_access_rules_group_id", table_name="access_rules")
    op.drop_index(
        "ix_access_rules_enabled", table_name="access_rules", postgresql_where=sa.text("enabled")
    )
    op.drop_table("access_rules")
    # ### end Alembic commands ###
