"""provisioning targets and links

The downstream systems we push accounts into, and a row per person per system saying
which account out there is theirs.

Two constraints carry the weight. One account per person per target, so a retry that
did not notice the first attempt succeeded cannot create a duplicate — duplicates in
somebody else's directory are the hardest kind to unpick, because both look real. And
one person per remote account, partial on remote_id being set, so two of our people
cannot both claim the same downstream account.

No backfill. Nothing was provisioning outward before this, so there is nothing to
adopt — unlike the role grants migration, where roles already existed on the user
row and needed a grant to stand on.

Revision ID: c4ee55d399f1
Revises: cd874ea16c13
Create Date: 2026-08-20 04:22:31.431969+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c4ee55d399f1"
down_revision: str | None = "cd874ea16c13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provisioning_targets",
        sa.Column(
            "application_id",
            sa.Uuid(),
            nullable=False,
            comment="Which application this provisions. Unique: one target per application, because two would race each other writing the same accounts.",
        ),
        sa.Column(
            "base_url",
            sa.String(length=500),
            nullable=False,
            comment="The downstream's SCIM root, e.g. https://example/scim/v2. Checked against ADR 0007 when it is set, not on every push.",
        ),
        sa.Column(
            "token_encrypted",
            sa.Text(),
            nullable=False,
            comment="The bearer token, encrypted. See iam/secrets.py for why this one is encrypted rather than hashed like the inbound tokens.",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Turning a target off stops pushes without losing the links, so turning it back on does not recreate every account.",
        ),
        sa.Column(
            "push_groups",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether to push group membership as well as accounts. Off by default: plenty of downstreams have no concept of a group, and sending them one is an error per person per sync.",
        ),
        sa.Column(
            "address_concession",
            sa.String(length=255),
            nullable=True,
            comment="A rule from ADR 0007 that was relaxed to allow this address — a private address, or plain HTTP. Stored so the page can show it was a decision rather than an oversight.",
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_sync_ok",
            sa.Boolean(),
            nullable=True,
            comment="Null means never tried. The useful question is the negative one: a target that last succeeded three weeks ago is one nobody is watching.",
        ),
        sa.Column(
            "last_error",
            sa.Text(),
            nullable=True,
            comment="Kept after a failure and cleared on success, so the page shows the current problem rather than a history of them.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_provisioning_targets_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provisioning_targets")),
        sa.UniqueConstraint("application_id", name=op.f("uq_provisioning_targets_application_id")),
    )
    op.create_table(
        "provisioning_links",
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "remote_id",
            sa.String(length=255),
            nullable=True,
            comment="The id the downstream gave this account. Null while a link exists but no account does yet — which is the state a failed create leaves behind, and is why a retry can tell 'never created' from 'created and then broke'.",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "active",
                "failed",
                "deprovisioned",
                "orphaned",
                name="linkstate",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("last_pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Consecutive failures. Reset on success. A link failing forever is worth telling somebody about rather than retrying quietly.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["provisioning_targets.id"],
            name=op.f("fk_provisioning_links_target_id_provisioning_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_provisioning_links_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("target_id", "user_id", name=op.f("pk_provisioning_links")),
        sa.UniqueConstraint("target_id", "user_id", name="one_account_per_person"),
    )
    op.create_index(
        "ix_provisioning_links_pending",
        "provisioning_links",
        ["target_id", "state"],
        unique=False,
        postgresql_where=sa.text("state <> 'active'"),
    )
    op.create_index(
        "one_person_per_remote_account",
        "provisioning_links",
        ["target_id", "remote_id"],
        unique=True,
        postgresql_where=sa.text("remote_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "one_person_per_remote_account",
        table_name="provisioning_links",
        postgresql_where=sa.text("remote_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_provisioning_links_pending",
        table_name="provisioning_links",
        postgresql_where=sa.text("state <> 'active'"),
    )
    op.drop_table("provisioning_links")
    op.drop_table("provisioning_targets")
    # ### end Alembic commands ###
