"""saml login: providers, request state, sessions, replay cache

Revision ID: 44b77077210a
Revises: 6ae303c8b4a1
Create Date: 2026-08-14 04:50:26.689999+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "44b77077210a"
down_revision: str | None = "6ae303c8b4a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_providers",
        sa.Column(
            "slug",
            sa.String(length=64),
            nullable=False,
            comment="Short name used in the login URL, e.g. /saml/login?idp=authentik",
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "entity_id",
            sa.String(length=500),
            nullable=False,
            comment="The provider's own id. Every login must say it came from this.",
        ),
        sa.Column(
            "sso_url",
            sa.String(length=500),
            nullable=False,
            comment="Where we send people to log in.",
        ),
        sa.Column(
            "slo_url",
            sa.String(length=500),
            nullable=True,
            comment="Where we send them to log out. Not all providers have one.",
        ),
        sa.Column(
            "signing_cert",
            sa.Text(),
            nullable=False,
            comment="The provider's certificate. This is the whole basis of trust: a login is only believed if it was signed with the matching key.",
        ),
        sa.Column(
            "want_signed_assertions",
            sa.Boolean(),
            nullable=False,
            comment="Whether to insist the assertion itself is signed, not just the response wrapped around it. Signing only the wrapper leaves room for swapping the contents, so this stays on unless a provider can't do it.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_providers")),
        sa.UniqueConstraint("entity_id", name=op.f("uq_identity_providers_entity_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_identity_providers_slug")),
    )
    op.create_table(
        "saml_assertion_seen",
        sa.Column("assertion_id", sa.String(length=255), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column(
            "not_on_or_after",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this login stops being valid, and so when we can forget it.",
        ),
        sa.Column(
            "seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Kept for the inspector: which session this became, who it was for.",
        ),
        sa.PrimaryKeyConstraint("assertion_id", name=op.f("pk_saml_assertion_seen")),
    )
    op.create_index(
        "ix_saml_assertion_seen_not_on_or_after",
        "saml_assertion_seen",
        ["not_on_or_after"],
        unique=False,
    )
    op.create_table(
        "saml_request_state",
        sa.Column(
            "relay_state",
            sa.String(length=64),
            nullable=False,
            comment="Random token we send with the request and get handed back.",
        ),
        sa.Column(
            "request_id",
            sa.String(length=128),
            nullable=False,
            comment="The id inside the login request we sent. The answer has to quote it back, which is what proves it's answering us and not arriving unprompted.",
        ),
        sa.Column("idp_slug", sa.String(length=64), nullable=False),
        sa.Column(
            "return_to",
            sa.String(length=500),
            nullable=False,
            comment="Where to send the person once they're in. Checked against a list of allowed paths before use, so this can't become an open redirect.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Rows past this are dead. Stops a request being answered hours later, and stops this table growing without limit.",
        ),
        sa.PrimaryKeyConstraint("relay_state", name=op.f("pk_saml_request_state")),
        sa.UniqueConstraint("request_id", name=op.f("uq_saml_request_state_request_id")),
    )
    op.create_index(
        "ix_saml_request_state_expires_at", "saml_request_state", ["expires_at"], unique=False
    )
    op.create_table(
        "saml_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of the cookie value. The cookie itself is never stored.",
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("idp_slug", sa.String(length=64), nullable=False),
        sa.Column(
            "name_id",
            sa.String(length=255),
            nullable=False,
            comment="How the provider identified this person in the login.",
        ),
        sa.Column("name_id_format", sa.String(length=200), nullable=True),
        sa.Column(
            "session_index",
            sa.String(length=255),
            nullable=True,
            comment="The provider's own name for this session. When it tells us someone logged out elsewhere, this is how we know which session it means.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set instead of deleting the row, so 'signed out at 14:32' stays answerable afterwards.",
        ),
        sa.Column("revoked_reason", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saml_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saml_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_saml_sessions_token_hash")),
    )
    op.create_index("ix_saml_sessions_expires_at", "saml_sessions", ["expires_at"], unique=False)
    op.create_index(
        "ix_saml_sessions_session_index", "saml_sessions", ["session_index"], unique=False
    )
    op.create_index("ix_saml_sessions_user_id", "saml_sessions", ["user_id"], unique=False)
    op.alter_column(
        "app_assignments",
        "role",
        existing_type=sa.VARCHAR(length=64),
        comment="What role this gives them in that app, for example 'Employee'.",
        existing_comment="Role granted inside the target application, e.g. 'Employee'.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "slug",
        existing_type=sa.VARCHAR(length=64),
        comment="Short name safe to put in a URL.",
        existing_comment="URL-safe identifier used in console routes.",
        existing_nullable=False,
    )
    op.alter_column(
        "applications",
        "entity_id",
        existing_type=sa.VARCHAR(length=500),
        comment="The app's SAML id. The spec says these are globally unique, so the unique constraint is just enforcing that.",
        existing_comment="SAML EntityID of the service provider. Globally unique by spec, so the constraint is the spec's, not ours.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "acs_url",
        existing_type=sa.VARCHAR(length=500),
        comment="Where we send the login response after someone signs in.",
        existing_comment="Assertion Consumer Service — where we POST the assertion.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "signing_cert",
        existing_type=sa.TEXT(),
        comment="The app's certificate, so we can check its requests are genuine.",
        existing_comment="The SP's X.509 certificate, PEM. Used to verify AuthnRequests.",
        existing_nullable=True,
    )
    op.alter_column(
        "audit_events",
        "actor_label",
        existing_type=sa.VARCHAR(length=255),
        comment="The person's name, copied in when the entry is written, so the entry still makes sense after their account is gone.",
        existing_comment="Human-readable actor, denormalised at write time so the entry still reads correctly after the actor is gone.",
        existing_nullable=False,
    )
    op.alter_column(
        "groups",
        "external_id",
        existing_type=sa.VARCHAR(length=255),
        comment="The id the identity provider uses for this group.",
        existing_comment="SCIM externalId for the group in the upstream IdP.",
        existing_nullable=True,
    )
    op.alter_column(
        "groups",
        "hrms_role",
        existing_type=sa.VARCHAR(length=64),
        comment="What role being in this group gives you in the HRMS. Set on the group, not per person, so you manage access by changing membership.",
        existing_comment="Role granted in the downstream HRMS by virtue of this membership. Group-derived rather than per-user, which is the whole point of group-based access.",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "external_id",
        existing_type=sa.VARCHAR(length=255),
        comment="The id the identity provider uses for this person.",
        existing_comment="SCIM externalId — the IdP's own identifier for this person.",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "user_name",
        existing_type=sa.VARCHAR(length=255),
        comment="What they log in with, usually their email. Doesn't change.",
        existing_comment="SCIM userName. Usually the UPN or email. Stable login identifier.",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "active",
        existing_type=sa.BOOLEAN(),
        comment="Switching this off is how we remove someone. We never delete the row, so you can still see what they had access to after they've left.",
        existing_comment="SCIM active. Deactivation is a soft delete — audit history and past access must remain inspectable after someone leaves.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "platform_role",
        existing_type=sa.VARCHAR(length=32),
        comment="What this person can do in the console. In P4 this gets worked out from their access grants instead of being stored here.",
        existing_comment="What this person can do in this console. P4 derives this from entitlement grants instead of storing it directly.",
        existing_nullable=False,
        existing_server_default=sa.text("'employee'::character varying"),
    )
    op.alter_column(
        "users",
        "source",
        existing_type=sa.VARCHAR(length=32),
        comment="Where this record came from. If SCIM created it, editing it here gets overwritten on the next sync, so the API refuses those edits.",
        existing_comment="Provenance. A SCIM-sourced user edited by hand will be silently reverted by the next sync, so the UI blocks it.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "source",
        existing_type=sa.VARCHAR(length=32),
        comment="Provenance. A SCIM-sourced user edited by hand will be silently reverted by the next sync, so the UI blocks it.",
        existing_comment="Where this record came from. If SCIM created it, editing it here gets overwritten on the next sync, so the API refuses those edits.",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "platform_role",
        existing_type=sa.VARCHAR(length=32),
        comment="What this person can do in this console. P4 derives this from entitlement grants instead of storing it directly.",
        existing_comment="What this person can do in the console. In P4 this gets worked out from their access grants instead of being stored here.",
        existing_nullable=False,
        existing_server_default=sa.text("'employee'::character varying"),
    )
    op.alter_column(
        "users",
        "active",
        existing_type=sa.BOOLEAN(),
        comment="SCIM active. Deactivation is a soft delete — audit history and past access must remain inspectable after someone leaves.",
        existing_comment="Switching this off is how we remove someone. We never delete the row, so you can still see what they had access to after they've left.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "user_name",
        existing_type=sa.VARCHAR(length=255),
        comment="SCIM userName. Usually the UPN or email. Stable login identifier.",
        existing_comment="What they log in with, usually their email. Doesn't change.",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "external_id",
        existing_type=sa.VARCHAR(length=255),
        comment="SCIM externalId — the IdP's own identifier for this person.",
        existing_comment="The id the identity provider uses for this person.",
        existing_nullable=True,
    )
    op.alter_column(
        "groups",
        "hrms_role",
        existing_type=sa.VARCHAR(length=64),
        comment="Role granted in the downstream HRMS by virtue of this membership. Group-derived rather than per-user, which is the whole point of group-based access.",
        existing_comment="What role being in this group gives you in the HRMS. Set on the group, not per person, so you manage access by changing membership.",
        existing_nullable=True,
    )
    op.alter_column(
        "groups",
        "external_id",
        existing_type=sa.VARCHAR(length=255),
        comment="SCIM externalId for the group in the upstream IdP.",
        existing_comment="The id the identity provider uses for this group.",
        existing_nullable=True,
    )
    op.alter_column(
        "audit_events",
        "actor_label",
        existing_type=sa.VARCHAR(length=255),
        comment="Human-readable actor, denormalised at write time so the entry still reads correctly after the actor is gone.",
        existing_comment="The person's name, copied in when the entry is written, so the entry still makes sense after their account is gone.",
        existing_nullable=False,
    )
    op.alter_column(
        "applications",
        "signing_cert",
        existing_type=sa.TEXT(),
        comment="The SP's X.509 certificate, PEM. Used to verify AuthnRequests.",
        existing_comment="The app's certificate, so we can check its requests are genuine.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "acs_url",
        existing_type=sa.VARCHAR(length=500),
        comment="Assertion Consumer Service — where we POST the assertion.",
        existing_comment="Where we send the login response after someone signs in.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "entity_id",
        existing_type=sa.VARCHAR(length=500),
        comment="SAML EntityID of the service provider. Globally unique by spec, so the constraint is the spec's, not ours.",
        existing_comment="The app's SAML id. The spec says these are globally unique, so the unique constraint is just enforcing that.",
        existing_nullable=True,
    )
    op.alter_column(
        "applications",
        "slug",
        existing_type=sa.VARCHAR(length=64),
        comment="URL-safe identifier used in console routes.",
        existing_comment="Short name safe to put in a URL.",
        existing_nullable=False,
    )
    op.alter_column(
        "app_assignments",
        "role",
        existing_type=sa.VARCHAR(length=64),
        comment="Role granted inside the target application, e.g. 'Employee'.",
        existing_comment="What role this gives them in that app, for example 'Employee'.",
        existing_nullable=True,
    )
    op.drop_index("ix_saml_sessions_user_id", table_name="saml_sessions")
    op.drop_index("ix_saml_sessions_session_index", table_name="saml_sessions")
    op.drop_index("ix_saml_sessions_expires_at", table_name="saml_sessions")
    op.drop_table("saml_sessions")
    op.drop_index("ix_saml_request_state_expires_at", table_name="saml_request_state")
    op.drop_table("saml_request_state")
    op.drop_index("ix_saml_assertion_seen_not_on_or_after", table_name="saml_assertion_seen")
    op.drop_table("saml_assertion_seen")
    op.drop_table("identity_providers")
    # ### end Alembic commands ###
