"""role grants

Adds the table that records who was given a console role, by whom, and until
when. ``users.platform_role`` stays where it is but stops being the real answer;
it becomes a cached copy that iam/access/roles.py maintains.

The interesting part is the backfill at the end. Every user already has a role on
their row, and after this migration those roles need a grant behind them or the
new table would say the demo admin is a plain employee. Nobody knows who granted
those or when — that is exactly the gap this table closes — so they are written as
source 'migrated' rather than pretending somebody decided them.

Revision ID: 7ba689707a21
Revises: 57ad7cd87d0d
Create Date: 2026-08-17 16:43:21.993941+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7ba689707a21"
down_revision: str | None = "57ad7cd87d0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_grants",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "helpdesk",
                "auditor",
                "employee",
                name="platformrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
            comment="Never 'employee' — that's the absence of a grant, not a grant.",
        ),
        sa.Column(
            "source",
            sa.Enum(
                "direct",
                "rule",
                "request",
                "seed",
                "migrated",
                name="grantsource",
                native_enum=False,
                length=32,
            ),
            server_default="direct",
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=True,
            comment="Why they were given it. Free text, because the real reasons don't fit a dropdown.",
        ),
        sa.Column("granted_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "granted_by_label",
            sa.String(length=255),
            nullable=False,
            comment="Copy of the granter's name, kept because the id goes null if they are ever deleted and 'granted by nobody' is not an acceptable answer.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When it stops applying on its own. Null means indefinite.",
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_by_label", sa.String(length=255), nullable=True),
        sa.Column(
            "revoked_reason",
            sa.String(length=200),
            nullable=True,
            comment="One of RevokedGrantReason, or free text for a person's own wording.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_id"],
            ["users.id"],
            name=op.f("fk_role_grants_granted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_id"],
            ["users.id"],
            name=op.f("fk_role_grants_revoked_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_role_grants_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_grants")),
    )
    op.create_index(
        "ix_role_grants_expiring",
        "role_grants",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL AND expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_role_grants_user_granted", "role_grants", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        "one_live_role_grant_per_user",
        "role_grants",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # Backfill: give every role that already exists a grant to stand on.
    #
    # Without this, anybody who was an admin before today reads as an employee the
    # first time the drift check runs, and the console's own admin locks itself
    # out. Employees are skipped because 'employee' is the absence of a grant.
    #
    # gen_random_uuid() rather than generating ids in Python: this has to work when
    # the migration is applied to a database this process never connects to.
    op.execute(
        """
        INSERT INTO role_grants (
            id, user_id, role, source, reason,
            granted_by_label, created_at, updated_at
        )
        SELECT
            gen_random_uuid(),
            id,
            platform_role,
            'migrated',
            'Role already present when grants were introduced. Who granted it, '
                || 'and when, was never recorded.',
            'a database migration',
            now(),
            now()
        FROM users
        WHERE platform_role <> 'employee'
        """
    )

    op.alter_column(
        "users",
        "platform_role",
        existing_type=sa.VARCHAR(length=32),
        comment="What this person can do in the console. A cached copy of their role grants — iam/access/roles.py is the only thing that writes it.",
        existing_comment="What this person can do in the console. In P4 this gets worked out from their access grants instead of being stored here.",
        existing_nullable=False,
        existing_server_default=sa.text("'employee'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "platform_role",
        existing_type=sa.VARCHAR(length=32),
        comment="What this person can do in the console. In P4 this gets worked out from their access grants instead of being stored here.",
        existing_comment="What this person can do in the console. A cached copy of their role grants — iam/access/roles.py is the only thing that writes it.",
        existing_nullable=False,
        existing_server_default=sa.text("'employee'::character varying"),
    )
    op.drop_index(
        "one_live_role_grant_per_user",
        table_name="role_grants",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_role_grants_user_granted", table_name="role_grants")
    op.drop_index(
        "ix_role_grants_expiring",
        table_name="role_grants",
        postgresql_where=sa.text("revoked_at IS NULL AND expires_at IS NOT NULL"),
    )
    op.drop_table("role_grants")
    # ### end Alembic commands ###
