"""scim clients: bearer tokens for inbound provisioning

Revision ID: 57ad7cd87d0d
Revises: 44b77077210a
Create Date: 2026-08-16 18:14:26.514391+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "57ad7cd87d0d"
down_revision: str | None = "44b77077210a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scim_clients",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="What to call it in the console, e.g. 'authentik (local)'.",
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of the bearer token. The token itself is shown once, when it is created, and never stored.",
        ),
        sa.Column(
            "enabled",
            sa.Boolean(),
            nullable=False,
            comment="Turning this off stops the sync without deleting the record of it having existed, which the audit log still refers to.",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Why this exists, for whoever finds it in six months.",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this token was last accepted. The useful question is the opposite one: a token that has not been used in months is one nobody would notice being stolen.",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set instead of deleting the row, so 'that sync stopped on the 3rd, because we revoked it' stays answerable.",
        ),
        sa.Column("revoked_reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scim_clients")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_scim_clients_token_hash")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scim_clients")
    # ### end Alembic commands ###
