/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One application, with its SAML wiring and assignments */
        get: operations["get_application_api_applications__app_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the audit log, newest first */
        get: operations["list_events_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify the hash chain
         * @description Check the log and report the first entry that doesn't add up.
         *
         *     A broken log still comes back as 200 with `valid: false`. The check itself
         *     worked, and what it found is the answer. A 500 would mean the check couldn't
         *     run, which is a different problem.
         */
        get: operations["verify_api_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Headline counts
         * @description All six counts in one trip to the database.
         *
         *     Six little subqueries inside one SELECT, instead of six separate queries. This
         *     is the first thing that loads on every visit, and six round trips to Supabase
         *     over the internet is a delay you can see. One isn't.
         */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups */
        get: operations["list_groups_api_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One group */
        get: operations["get_group_api_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page through a group's members */
        get: operations["list_members_api_groups__group_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Say that the app is up.
         *
         *     Doesn't touch the database, so a database outage can't get a perfectly healthy
         *     container killed. It's also cheap enough for the frontend to call on page load
         *     to wake the API up.
         */
        get: operations["liveness_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Check that Postgres answers a trivial query.
         *
         *     Returns 503 if it doesn't, so a load balancer stops sending traffic here
         *     instead of letting requests fail.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the providers we accept logins from
         * @description Every registered provider, enabled or not.
         *
         *     Not paginated. There are three of these at most, and there is never going to
         *     be a fourth page of identity providers.
         */
        get: operations["list_identity_providers_api_identity_providers_get"];
        put?: never;
        /**
         * Register a provider from its metadata, or update one
         * @description Read a provider's metadata and store what it says.
         *
         *     Registering the same slug again replaces the details, which is what makes this
         *     the way to handle a certificate rotation: paste the new metadata, and the row
         *     updates. It's a POST that isn't a create-only, on purpose — a separate "update"
         *     endpoint would take the same document and do the same work, and having two
         *     would just mean guessing which one to use.
         *
         *     Rotations are worth watching, so the audit entry records the old and new
         *     certificate fingerprints whenever the key changes. A key changing when nobody
         *     rotated one is exactly the event you want to find in a log.
         *
         *     Raises:
         *         HTTPException: 400 if the metadata can't be read or is missing something.
         *             409 if another slug has already claimed the same entity id.
         */
        post: operations["register_identity_provider_api_identity_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity-providers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One provider, with its certificate */
        get: operations["get_identity_provider_api_identity_providers__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The person this request is coming from
         * @description Report the current person.
         *
         *     No permission check on this one on purpose: everybody is allowed to know who
         *     they are. Being signed in at all is the only requirement, and that's what
         *     resolving the actor already established.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saml/logins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every sign-in attempt, newest first
         * @description Logins in the order they happened, most recent first.
         *
         *     Cursors rather than page numbers, for the same reason the audit log uses them:
         *     new attempts arrive at the top, and page numbers would shift under you.
         */
        get: operations["list_login_attempts_api_saml_logins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saml/logins/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One attempt, with the assertion that arrived
         * @description One login, including the document itself when we kept it.
         *
         *     Only failures keep the document. A login that passed all ten checks has nothing
         *     to look at, and storing an assertion per login forever is a lot of somebody's
         *     personal data for no reason.
         *
         *     The XML comes back as it arrived rather than reformatted. An inspector exists to
         *     show what was actually sent — reformatting is the one thing it shouldn't do.
         */
        get: operations["get_login_attempt_api_saml_logins__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description The user list, filtered and split into pages.
         *
         *     The filtering and paging happen in Postgres, not the browser. There are 1,284
         *     users in the demo data; sending all of them so the frontend can filter would
         *     be slow, and it would also hand out every record to anyone who can load one
         *     page.
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One user, with effective access */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Change some fields on a user and write down what changed.
         *
         *     Raises:
         *         HTTPException: 409 if the field belongs to the identity provider and this
         *             user came from SCIM.
         */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add a user to a group
         * @description Safe to call twice. Adding someone already in the group just does nothing.
         */
        put: operations["add_to_group_api_users__user_id__groups__group_id__put"];
        post?: never;
        /** Remove a user from a group */
        delete: operations["remove_from_group_api_users__user_id__groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/acs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Where the provider posts the answer
         * @description Accept a login from the provider, or refuse it and say which check failed.
         *
         *     This is the endpoint that has to be right. Everything the provider sends
         *     arrives through the person's own browser, so all of it is under the control of
         *     whoever is trying to get in. Nothing here is trusted until it has been through
         *     every check in checks.py, and nothing is trusted a second time because the
         *     request it answers is consumed whether the login is accepted or not.
         *
         *     The order is: find the request this is answering, work out which provider that
         *     was, read and verify the document, run every check, and only then look up a
         *     person. Reading identity out of a document before checking it is the mistake
         *     that makes all the other checks pointless.
         *
         *     Only replies to logins we started. A provider can also start one by itself,
         *     from a tile in its own dashboard, and that has no request to match against —
         *     which means giving up the check that stops someone posting a login at us out
         *     of the blue. checks.py handles that case, so turning it on later is a small
         *     change, but it stays off until there's a reason to want it.
         *
         *     Raises:
         *         HTTPException: 400 for a login that can't be matched, read, or identified.
         *             401 for one that fails a check. 403 for a deactivated account.
         */
        post: operations["assertion_consumer_service_saml_acs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start signing in
         * @description Send someone to their provider to sign in.
         *
         *     Three things happen before the redirect: we check the provider is one we know,
         *     we check where they've asked to be sent afterwards, and we write down the
         *     request so the answer can be matched to it later.
         *
         *     That last part is why this can't be stateless. The answer arrives as a
         *     cross-site form POST and browsers don't send our cookies on those, so the
         *     request has to be remembered server-side, keyed by a token that travels with it.
         */
        get: operations["login_saml_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description End this session, clear the cookie, and tell the provider.
         *
         *     A POST, not a GET. A sign-out you can trigger with a link means any page on
         *     the internet can sign our users out with an image tag pointed at it. Annoying
         *     rather than dangerous, but it costs nothing to get right, and the Lax cookie
         *     means a cross-site POST doesn't carry the session anyway.
         *
         *     If the provider has a logout address, this ends with a redirect to it carrying
         *     a LogoutRequest, and the provider signs them out too. Without that step,
         *     clicking login again puts them straight back in without a password prompt,
         *     because the provider still thinks they're signed in — which is a surprising
         *     thing to watch happen right after pressing "sign out".
         *
         *     Our own session is ended before the redirect, not after. If the provider is
         *     down or never answers, the person is still signed out here, which is the part
         *     we're responsible for.
         *
         *     Always succeeds. No cookie, an unknown one, one that expired an hour ago:
         *     they all end with the person signed out and the cookie gone, which is what
         *     they asked for. Reporting an error for "you were already signed out" would be
         *     technically accurate and useless.
         */
        post: operations["logout_saml_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Our details, for registering this app with a provider
         * @description Hand this to whoever runs the identity provider.
         *
         *     Deliberately not behind a login. It contains nothing secret — just our name and
         *     the address to send answers to — and needing to be signed in to fetch the thing
         *     you need in order to sign in would be an awkward loop.
         */
        get: operations["metadata_saml_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saml/sls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single logout, in both directions
         * @description Handle a logout, whichever side started it.
         *
         *     Two different things arrive here and they are told apart by which parameter is
         *     present, not by the method:
         *
         *     A `SAMLResponse` is the provider confirming it signed somebody out because we
         *     asked. Our session was already ended before we sent that request, so there's
         *     nothing left to do but check it and send the person home.
         *
         *     A `SAMLRequest` is the provider telling us somebody signed out somewhere else,
         *     or was signed out by an administrator. That one matters: it's the message that
         *     makes "remove their access" actually remove their access, everywhere, rather
         *     than only in the places they happen to visit next.
         *
         *     Accepts GET and POST because providers differ on which they use, and the message
         *     is the same either way.
         *
         *     We don't sign our answer. A provider that insists on signed logout messages
         *     won't accept it, and that needs a key of ours, which arrives in P5. authentik
         *     doesn't insist, so this works today; Okta and Entra may not, and that's a known
         *     limit rather than a surprise.
         *
         *     Unsigned requests are refused. We can't tell who sent one, and accepting it
         *     would let anybody sign out anybody whose NameID they can guess. That's only a
         *     nuisance rather than a way in, but refusing costs nothing.
         */
        get: operations["single_logout_redirect_binding"];
        put?: never;
        /**
         * Single logout, in both directions
         * @description Handle a logout, whichever side started it.
         *
         *     Two different things arrive here and they are told apart by which parameter is
         *     present, not by the method:
         *
         *     A `SAMLResponse` is the provider confirming it signed somebody out because we
         *     asked. Our session was already ended before we sent that request, so there's
         *     nothing left to do but check it and send the person home.
         *
         *     A `SAMLRequest` is the provider telling us somebody signed out somewhere else,
         *     or was signed out by an administrator. That one matters: it's the message that
         *     makes "remove their access" actually remove their access, everywhere, rather
         *     than only in the places they happen to visit next.
         *
         *     Accepts GET and POST because providers differ on which they use, and the message
         *     is the same either way.
         *
         *     We don't sign our answer. A provider that insists on signed logout messages
         *     won't accept it, and that needs a key of ours, which arrives in P5. authentik
         *     doesn't insist, so this works today; Okta and Entra may not, and that's a known
         *     limit rather than a surprise.
         *
         *     Unsigned requests are refused. We can't tell who sent one, and accepting it
         *     would let anybody sign out anybody whose NameID they can guess. That's only a
         *     nuisance rather than a way in, but refusing costs nothing.
         */
        post: operations["single_logout_post_binding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorType
         * @description What kind of thing did this.
         * @enum {string}
         */
        ActorType: "user" | "system" | "idp";
        /**
         * AppProtocol
         * @description How an application integrates with this control plane.
         * @enum {string}
         */
        AppProtocol: "saml2" | "oidc" | "scim2" | "none";
        /**
         * AppRef
         * @description An app someone can get into, and what role it gives them.
         */
        AppRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            protocol: components["schemas"]["AppProtocol"];
            /**
             * Role
             * @description What role this access gives them inside the app.
             */
            role?: string | null;
            /** Slug */
            slug: string;
            /**
             * Via Group
             * @description The group that gives them this access, or null if it was given to them directly. Answers 'why does this person have Salesforce?'
             */
            via_group?: string | null;
        };
        /**
         * AppStatus
         * @enum {string}
         */
        AppStatus: "active" | "inactive";
        /**
         * ApplicationDetail
         * @description Everything on the app page, including its SAML settings.
         *
         *     Nothing uses the SAML fields until P5. They're here because the console shows
         *     them, and a mistyped entity id is much easier to spot on a page than by
         *     reading the database.
         */
        ApplicationDetail: {
            /** Acs Url */
            acs_url: string | null;
            /** Assigned Groups */
            assigned_groups: components["schemas"]["GroupRef"][];
            /** Assigned Users */
            assigned_users: components["schemas"]["UserRef"][];
            /** Assignment Count */
            assignment_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Entity Id */
            entity_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Nameid Format */
            nameid_format: string | null;
            protocol: components["schemas"]["AppProtocol"];
            /**
             * Signing Cert
             * @description The SP's public certificate. Public by definition — it is published in SAML metadata — so this is not a secret being leaked.
             */
            signing_cert?: string | null;
            /** Slo Url */
            slo_url: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["AppStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApplicationSummary */
        ApplicationSummary: {
            /** Assignment Count */
            assignment_count: number;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            protocol: components["schemas"]["AppProtocol"];
            /** Slug */
            slug: string;
            status: components["schemas"]["AppStatus"];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Label */
            actor_label: string;
            actor_type: components["schemas"]["ActorType"];
            /** Correlation Id */
            correlation_id: string | null;
            /** Detail */
            detail: Record<string, never>;
            /** Hash */
            hash: string;
            /** Id */
            id: number;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            outcome: components["schemas"]["AuditOutcome"];
            /** Prev Hash */
            prev_hash: string;
            /** Target Id */
            target_id: string | null;
            /** Target Label */
            target_label: string | null;
            /** Target Type */
            target_type: string | null;
        };
        /**
         * AuditOutcome
         * @enum {string}
         */
        AuditOutcome: "success" | "failure" | "denied";
        /** Body_assertion_consumer_service_saml_acs_post */
        Body_assertion_consumer_service_saml_acs_post: {
            /** Relay State */
            relay_state?: string | null;
            /** Saml Response */
            saml_response: string;
        };
        /**
         * ChainVerification
         * @description What the tamper check found.
         */
        ChainVerification: {
            /**
             * Broken At Id
             * @description The first entry that didn't add up, if there was one.
             */
            broken_at_id?: number | null;
            /** Events Checked */
            events_checked: number;
            /**
             * Reason
             * @description What was wrong with it.
             */
            reason?: string | null;
            /** Valid */
            valid: boolean;
        };
        /** CursorPage[AuditEventOut] */
        CursorPage_AuditEventOut_: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Limit */
            limit: number;
            /**
             * Next Cursor
             * @description Pass as `cursor` to fetch the following page. Null at the end.
             */
            next_cursor?: string | null;
        };
        /** CursorPage[LoginAttempt] */
        CursorPage_LoginAttempt_: {
            /** Items */
            items: components["schemas"]["LoginAttempt"][];
            /** Limit */
            limit: number;
            /**
             * Next Cursor
             * @description Pass as `cursor` to fetch the following page. Null at the end.
             */
            next_cursor?: string | null;
        };
        /**
         * DashboardCounts
         * @description The numbers on the front page.
         */
        DashboardCounts: {
            /** Active Users */
            active_users: number;
            /** Applications */
            applications: number;
            /** Audit Events */
            audit_events: number;
            /** Groups */
            groups: number;
            /**
             * Sso Applications
             * @description How many of the apps use SAML login. Part of `applications`.
             */
            sso_applications: number;
            /** Users */
            users: number;
        };
        /** GroupDetail */
        GroupDetail: {
            /** Applications */
            applications: components["schemas"]["AppRef"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** External Id */
            external_id: string | null;
            /** Hrms Role */
            hrms_role: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Member Count */
            member_count: number;
            /**
             * Members
             * @description Only the first page of members. Use /api/groups/{id}/members to page through a big group.
             */
            members: components["schemas"]["UserRef"][];
            /** Name */
            name: string;
            source: components["schemas"]["IdentitySource"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GroupRef
         * @description Just enough of a group to link to it.
         */
        GroupRef: {
            /** Hrms Role */
            hrms_role?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** GroupSummary */
        GroupSummary: {
            /** Description */
            description: string | null;
            /** Hrms Role */
            hrms_role: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Member Count */
            member_count: number;
            /** Name */
            name: string;
            source: components["schemas"]["IdentitySource"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityProviderDetail
         * @description One provider, including the certificate in full.
         */
        IdentityProviderDetail: {
            /**
             * Certificate Fingerprint
             * @description The first and last few characters of the signing certificate. Enough to see at a glance that the key has changed, which is otherwise a diff of two blocks of base64.
             */
            certificate_fingerprint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Login Url
             * @description Where to send somebody to sign in with this provider.
             */
            login_url: string;
            /** Name */
            name: string;
            /**
             * Signing Cert
             * @description The certificate every login from this provider is checked against. This is the whole basis of trust for it.
             */
            signing_cert: string;
            /** Slo Url */
            slo_url: string | null;
            /** Slug */
            slug: string;
            /** Sso Url */
            sso_url: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Want Signed Assertions */
            want_signed_assertions: boolean;
        };
        /**
         * IdentityProviderRegistration
         * @description Register a provider, or update one that already exists.
         *
         *     The metadata document carries the entity id, the addresses and the
         *     certificate, so none of those are fields here. Letting somebody type them
         *     separately is how you end up trusting a key the provider never published.
         *     See docs/adr/0006-paste-metadata-do-not-fetch-it.md.
         */
        IdentityProviderRegistration: {
            /**
             * Enabled
             * @description Turn a provider off to stop new logins without losing its settings.
             * @default true
             */
            enabled: boolean;
            /**
             * Metadata Xml
             * @description The provider's SAML metadata document, pasted in whole.
             */
            metadata_xml: string;
            /**
             * Name
             * @description What to call it in the console.
             */
            name: string;
            /**
             * Slug
             * @description Short name used in the login URL, e.g. /saml/login?idp=authentik. Lowercase, digits and dashes, because it goes in a query string.
             */
            slug: string;
            /**
             * Want Signed Assertions
             * @description Insist the assertion itself is signed, not just the response wrapped around it. Only turn this off for a provider that genuinely cannot do it, because signing only the wrapper leaves the contents swappable.
             * @default true
             */
            want_signed_assertions: boolean;
        };
        /**
         * IdentityProviderSummary
         * @description A registered provider, without the wall of base64.
         */
        IdentityProviderSummary: {
            /**
             * Certificate Fingerprint
             * @description The first and last few characters of the signing certificate. Enough to see at a glance that the key has changed, which is otherwise a diff of two blocks of base64.
             */
            certificate_fingerprint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Entity Id */
            entity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Login Url
             * @description Where to send somebody to sign in with this provider.
             */
            login_url: string;
            /** Name */
            name: string;
            /** Slo Url */
            slo_url: string | null;
            /** Slug */
            slug: string;
            /** Sso Url */
            sso_url: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Want Signed Assertions */
            want_signed_assertions: boolean;
        };
        /**
         * IdentitySource
         * @description Where a record came from.
         *
         *     Worth tracking, because you shouldn't hand-edit something SCIM created. The
         *     next sync would just put it back.
         * @enum {string}
         */
        IdentitySource: "scim" | "jit" | "manual" | "seed";
        /**
         * Liveness
         * @description Is the app running. Doesn't check anything outside the process.
         */
        Liveness: {
            /**
             * Env
             * @description Which environment this is
             */
            env: string;
            /**
             * Git Sha
             * @description The commit this build came from
             */
            git_sha: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description App version
             */
            version: string;
        };
        /**
         * LoginAttempt
         * @description One login, accepted or refused.
         *
         *     A single pass/fail tells you nothing when a login mysteriously stops working
         *     against a new provider. Ten named results tell you it was the clock.
         */
        LoginAttempt: {
            /** Assertion Id */
            assertion_id?: string | null;
            /** Checks */
            checks: components["schemas"]["LoginCheck"][];
            /**
             * Directory
             * @description What the login did to the directory: created somebody, refreshed their details, or nothing.
             */
            directory?: string | null;
            /**
             * Failed Checks
             * @description Names of the checks that did not pass.
             */
            failed_checks: string[];
            /**
             * Has Response
             * @description Whether the assertion itself was kept. Only failures keep it — a login that passed every check has nothing to look at.
             */
            has_response: boolean;
            /**
             * Id
             * @description The audit entry this came from.
             */
            id: number;
            /**
             * Idp
             * @description Which provider, by short name.
             */
            idp?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            outcome: components["schemas"]["AuditOutcome"];
            /**
             * Reason
             * @description Why it was refused.
             */
            reason?: string | null;
            /**
             * Session Id
             * @description The session this login became, if it was accepted.
             */
            session_id?: string | null;
            /**
             * Who
             * @description The person on a successful login, the provider on a failed one.
             */
            who: string;
        };
        /**
         * LoginAttemptDetail
         * @description One login, with the document that arrived.
         */
        LoginAttemptDetail: {
            /** Assertion Id */
            assertion_id?: string | null;
            /** Checks */
            checks: components["schemas"]["LoginCheck"][];
            /**
             * Decoded Response
             * @description The assertion as it arrived, decoded but not reformatted. An inspector should show what was actually sent, not a tidied-up version of it.
             */
            decoded_response: string | null;
            /**
             * Directory
             * @description What the login did to the directory: created somebody, refreshed their details, or nothing.
             */
            directory?: string | null;
            /**
             * Failed Checks
             * @description Names of the checks that did not pass.
             */
            failed_checks: string[];
            /**
             * Has Response
             * @description Whether the assertion itself was kept. Only failures keep it — a login that passed every check has nothing to look at.
             */
            has_response: boolean;
            /**
             * Id
             * @description The audit entry this came from.
             */
            id: number;
            /**
             * Idp
             * @description Which provider, by short name.
             */
            idp?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            outcome: components["schemas"]["AuditOutcome"];
            /**
             * Reason
             * @description Why it was refused.
             */
            reason?: string | null;
            /**
             * Response Truncated
             * @description Whether the stored copy was cut short.
             */
            response_truncated: boolean;
            /**
             * Session Id
             * @description The session this login became, if it was accepted.
             */
            session_id?: string | null;
            /**
             * Who
             * @description The person on a successful login, the provider on a failed one.
             */
            who: string;
        };
        /**
         * LoginCheck
         * @description One of the ten checks, and how it went.
         */
        LoginCheck: {
            /**
             * Detail
             * @description Why it passed or failed, in words. The useful part when it failed.
             */
            detail: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /** Page[ApplicationSummary] */
        Page_ApplicationSummary_: {
            /** Items */
            items: components["schemas"]["ApplicationSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description How many rows match the filters, ignoring paging.
             */
            total: number;
        };
        /** Page[GroupSummary] */
        Page_GroupSummary_: {
            /** Items */
            items: components["schemas"]["GroupSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description How many rows match the filters, ignoring paging.
             */
            total: number;
        };
        /** Page[UserRef] */
        Page_UserRef_: {
            /** Items */
            items: components["schemas"]["UserRef"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description How many rows match the filters, ignoring paging.
             */
            total: number;
        };
        /** Page[UserSummary] */
        Page_UserSummary_: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description How many rows match the filters, ignoring paging.
             */
            total: number;
        };
        /**
         * PlatformRole
         * @description What someone can do inside this console.
         *
         *     Four broad roles, stored straight on the user for now. P4 works them out from
         *     someone's access grants instead, and this column becomes a cached copy rather
         *     than the real answer.
         * @enum {string}
         */
        PlatformRole: "admin" | "helpdesk" | "auditor" | "employee";
        /**
         * Readiness
         * @description Is the app able to do its job, i.e. can it reach the database.
         */
        Readiness: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unreachable";
            /**
             * Detail
             * @description The kind of error, if any. Never the connection string.
             */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /**
         * SignedInUser
         * @description Who the console is talking to, and what they can do.
         *
         *     The permissions are sent as a list so the front end can hide buttons nobody
         *     can use. It is only ever a nicety: every one of them is checked again on the
         *     request, because a hidden button is not a permission check.
         */
        SignedInUser: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Permissions */
            permissions: string[];
            role: components["schemas"]["PlatformRole"];
            /** User Name */
            user_name: string;
            /**
             * Via Saml Session
             * @description True when this came from a real login. False means the development stand-in identified the request, which never happens in production.
             */
            via_saml_session: boolean;
        };
        /**
         * UserDetail
         * @description Everything about one person, including what they can get into.
         */
        UserDetail: {
            /** Active */
            active: boolean;
            /**
             * Applications
             * @description Everything they can actually get into: given to them directly plus anything that comes from a group they're in.
             */
            applications: components["schemas"]["AppRef"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Department */
            department: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Employee Number */
            employee_number: string | null;
            /** External Id */
            external_id: string | null;
            /** Family Name */
            family_name: string | null;
            /** Given Name */
            given_name: string | null;
            /** Groups */
            groups: components["schemas"]["GroupRef"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Title */
            job_title: string | null;
            manager: components["schemas"]["UserRef"] | null;
            platform_role: components["schemas"]["PlatformRole"];
            source: components["schemas"]["IdentitySource"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Name */
            user_name: string;
        };
        /**
         * UserRef
         * @description Just enough of a user to link to them.
         */
        UserRef: {
            /** Active */
            active: boolean;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Name */
            user_name: string;
        };
        /**
         * UserSummary
         * @description One row in the user list.
         */
        UserSummary: {
            /** Active */
            active: boolean;
            /** Department */
            department: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Title */
            job_title: string | null;
            platform_role: components["schemas"]["PlatformRole"];
            source: components["schemas"]["IdentitySource"];
            /** User Name */
            user_name: string;
        };
        /**
         * UserUpdate
         * @description The fields you're allowed to change. Leave a field out and it stays as is.
         *
         *     A short list on purpose. Login name, email and external id belong to the
         *     identity provider for anyone it created, so editing them here would just get
         *     undone on the next sync.
         */
        UserUpdate: {
            /** Active */
            active?: boolean | null;
            /** Department */
            department?: string | null;
            /** Job Title */
            job_title?: string | null;
            platform_role?: components["schemas"]["PlatformRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                /** @description Match name or slug */
                q?: string | null;
                protocol?: components["schemas"]["AppProtocol"] | null;
                status?: components["schemas"]["AppStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_applications__app_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_audit_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                /** @description Exact action, e.g. user.updated */
                action?: string | null;
                outcome?: components["schemas"]["AuditOutcome"] | null;
                actor_id?: string | null;
                target_type?: string | null;
                correlation_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage_AuditEventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_audit_verify_get: {
        parameters: {
            query?: {
                /** @description Stop after this many events. Omit to verify everything. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardCounts"];
                };
            };
        };
    };
    list_groups_api_groups_get: {
        parameters: {
            query?: {
                /** @description Match group name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_group_api_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_groups__group_id__members_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRef_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    list_identity_providers_api_identity_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderSummary"][];
                };
            };
        };
    };
    register_identity_provider_api_identity_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityProviderRegistration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_identity_provider_api_identity_providers__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedInUser"];
                };
            };
        };
    };
    list_login_attempts_api_saml_logins_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page */
                cursor?: string | null;
                /** @description Narrow to just the failures, usually */
                outcome?: components["schemas"]["AuditOutcome"] | null;
                /** @description Only this provider, by short name */
                idp?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage_LoginAttempt_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_login_attempt_api_saml_logins__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginAttemptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                /** @description Match name, userName or email */
                q?: string | null;
                active?: boolean | null;
                department?: string | null;
                platform_role?: components["schemas"]["PlatformRole"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_group_api_users__user_id__groups__group_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_group_api_users__user_id__groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assertion_consumer_service_saml_acs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_assertion_consumer_service_saml_acs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_saml_login_get: {
        parameters: {
            query?: {
                /** @description Which provider to use, by short name */
                idp?: string;
                /** @description Where to land afterwards */
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_saml_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metadata_saml_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/samlmetadata+xml": unknown;
                };
            };
        };
    };
    single_logout_redirect_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    single_logout_post_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
